### ISSUE TITLE
Priority of modulo operator vs. equality operator is wrong

### ISSUE THREAD

**Issue by ffleurey** [TelluIoT/ThingML#211] opened 2018-03-22 15:03 UTC
my_var % 10 == 0 seems to be parsed as my_var % (10 == 0) instead of (my_var % 10) == 0

the workaround is to always use the parenthesis but we should probably fix this at some point. I do not know how many other operators are affected. We should have some tests for this.

**Comment by brice-morin** [comment] 2018-03-22 18:36
Duplicate of #178 :-)

**Closed by brice-morin** 2018-03-22 18:36 UTC
Labels: Bug, language/Parser
